name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5 # Gestión de estado reactivo y navegación
  http: ^0.13.5 # Manejo de solicitudes HTTP
  provider: ^6.0.5 # Manejo de estado adicional
  cupertino_icons: ^1.0.5 # Íconos para diseño iOS
  dio: ^5.2.0 # Cliente HTTP más avanzado
  flutter_lints: ^2.0.1 # Reglas de linting
  json_annotation: ^4.8.1 # Para manejar JSON en modelos

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6 # Para generar archivos automáticos
  json_serializable: ^6.6.1 # Serialización y deserialización JSON
  flutter_lints: ^2.0.1 # Reglas de linting

flutter:
  uses-material-design: true
